
const blogs = [
  { "id" : 0,"author" : "deneme 1", "date" : "21 Temmuz 2021" ,"title" : "deneme 1", "description" : "deniyoz lalalalalallallalalalalallala","srcImage" : "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80","amountOfLikes" : 0,"avatar" : "/svg/logosoy-2.svg", "comments" : [ 
    { "author" : "Selam 1", "text" : "Lorem sıdhs sdhajsdn sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }, 
    { "author" : "Selam 2", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "" }, 
    { "author" : "Selam 3", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }
  ],"text" : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales ipsum quis accumsan pellentesque. Aliquam fringilla pharetra scelerisque. Vestibulum vel dolor quis lacus laoreet faucibus in a purus. In imperdiet vulputate ullamcorper. Nam ultricies consectetur libero vitae faucibus. Nam luctus eros nec mattis iaculis. Proin in sodales metus. In facilisis suscipit elementum. Nulla tristique quis arcu id pulvinar. Aenean eu faucibus nisi. In ex elit, sollicitudin ac eros id, malesuada auctor sapien. Curabitur eros dui, finibus nec fermentum quis, pellentesque id orci. Nullam eu tempus nulla. Vestibulum vitae metus nunc. Nullam quam magna, molestie at ultricies sit amet, sodales eget lacus. Maecenas ut nibh dictum, convallis elit nec, laoreet libero. Vivamus tempor porta lectus sit amet ornare. Vivamus at tellus et nulla consequat mollis quis vitae nisi. Curabitur sed lectus diam. Curabitur sodales vel justo ut pulvinar.  Curabitur vel imperdiet nulla. Integer venenatis dolor dui, non ultrices massa porta sed. Nunc egestas lacus eget ipsum lacinia egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur varius volutpat lacus eget euismod. Etiam ullamcorper ex augue, vel tempor sem varius eget. Nullam quis feugiat quam, nec lobortis enim. Duis mollis nunc id mi facilisis, quis laoreet est imperdiet. Integer dignissim accumsan eros. Morbi commodo tortor vel tortor tristique mollis. Duis ut elit gravida, rutrum diam id, ullamcorper dolor. Curabitur scelerisque justo a erat elementum, eget faucibus felis consequat. Phasellus convallis fringilla purus, non dapibus augue gravida at. Nulla lacinia maximus libero, ut cursus urna accumsan sed.</p>", "likedProfiles" : []  },
  { "id" : 1,"author" : "deneme 1", "date" : "21 Temmuz 2021" ,"title" : "deneme 2", "description" : "deniyoz lalalalalallallalalalalallala","srcImage" : "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80","amountOfLikes" : 1,"avatar" : "", "comments" : [ 
    { "author" : "Selam 1", "text" : "Lorem sıdhs sdhajsdn sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }, 
    { "author" : "Selam 2", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "" }, 
    { "author" : "Selam 3", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }
  ],"text" : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales ipsum quis accumsan pellentesque. Aliquam fringilla pharetra scelerisque. Vestibulum vel dolor quis lacus laoreet faucibus in a purus. In imperdiet vulputate ullamcorper. Nam ultricies consectetur libero vitae faucibus. Nam luctus eros nec mattis iaculis. Proin in sodales metus. In facilisis suscipit elementum. Nulla tristique quis arcu id pulvinar. Aenean eu faucibus nisi. In ex elit, sollicitudin ac eros id, malesuada auctor sapien. Curabitur eros dui, finibus nec fermentum quis, pellentesque id orci. Nullam eu tempus nulla. Vestibulum vitae metus nunc. Nullam quam magna, molestie at ultricies sit amet, sodales eget lacus. Maecenas ut nibh dictum, convallis elit nec, laoreet libero. Vivamus tempor porta lectus sit amet ornare. Vivamus at tellus et nulla consequat mollis quis vitae nisi. Curabitur sed lectus diam. Curabitur sodales vel justo ut pulvinar.  Curabitur vel imperdiet nulla. Integer venenatis dolor dui, non ultrices massa porta sed. Nunc egestas lacus eget ipsum lacinia egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur varius volutpat lacus eget euismod. Etiam ullamcorper ex augue, vel tempor sem varius eget. Nullam quis feugiat quam, nec lobortis enim. Duis mollis nunc id mi facilisis, quis laoreet est imperdiet. Integer dignissim accumsan eros. Morbi commodo tortor vel tortor tristique mollis. Duis ut elit gravida, rutrum diam id, ullamcorper dolor. Curabitur scelerisque justo a erat elementum, eget faucibus felis consequat. Phasellus convallis fringilla purus, non dapibus augue gravida at. Nulla lacinia maximus libero, ut cursus urna accumsan sed.</p>", "likedProfiles" : [10] },
  { "id" : 2,"author" : "deneme 1", "date" : "21 Temmuz 2021" ,"title" : "deneme 3", "description" : "deniyoz lalalalalallallalalalalallala","srcImage" : "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80","amountOfLikes" : 0,"avatar" : "/svg/logosoy-2.svg", "comments" : [ 
    { "author" : "Selam 1", "text" : "Lorem sıdhs sdhajsdn sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }, 
    { "author" : "Selam 2", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "" }, 
    { "author" : "Selam 3", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }
  ],"text" : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales ipsum quis accumsan pellentesque. Aliquam fringilla pharetra scelerisque. Vestibulum vel dolor quis lacus laoreet faucibus in a purus. In imperdiet vulputate ullamcorper. Nam ultricies consectetur libero vitae faucibus. Nam luctus eros nec mattis iaculis. Proin in sodales metus. In facilisis suscipit elementum. Nulla tristique quis arcu id pulvinar. Aenean eu faucibus nisi. In ex elit, sollicitudin ac eros id, malesuada auctor sapien. Curabitur eros dui, finibus nec fermentum quis, pellentesque id orci. Nullam eu tempus nulla. Vestibulum vitae metus nunc. Nullam quam magna, molestie at ultricies sit amet, sodales eget lacus. Maecenas ut nibh dictum, convallis elit nec, laoreet libero. Vivamus tempor porta lectus sit amet ornare. Vivamus at tellus et nulla consequat mollis quis vitae nisi. Curabitur sed lectus diam. Curabitur sodales vel justo ut pulvinar.  Curabitur vel imperdiet nulla. Integer venenatis dolor dui, non ultrices massa porta sed. Nunc egestas lacus eget ipsum lacinia egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur varius volutpat lacus eget euismod. Etiam ullamcorper ex augue, vel tempor sem varius eget. Nullam quis feugiat quam, nec lobortis enim. Duis mollis nunc id mi facilisis, quis laoreet est imperdiet. Integer dignissim accumsan eros. Morbi commodo tortor vel tortor tristique mollis. Duis ut elit gravida, rutrum diam id, ullamcorper dolor. Curabitur scelerisque justo a erat elementum, eget faucibus felis consequat. Phasellus convallis fringilla purus, non dapibus augue gravida at. Nulla lacinia maximus libero, ut cursus urna accumsan sed.</p>", "likedProfiles" : [] },
  { "id" : 3,"author" : "deneme 1", "date" : "21 Temmuz 2021" ,"title" : "deneme 4", "description" : "deniyoz lalalalalallallalalalalallala","srcImage" : "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80","amountOfLikes" : 1,"avatar" : "", "comments" : [ 
    { "author" : "Selam 1", "text" : "Lorem sıdhs sdhajsdn sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }, 
    { "author" : "Selam 2", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "" }, 
    { "author" : "Selam 3", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }
  ],"text" : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales ipsum quis accumsan pellentesque. Aliquam fringilla pharetra scelerisque. Vestibulum vel dolor quis lacus laoreet faucibus in a purus. In imperdiet vulputate ullamcorper. Nam ultricies consectetur libero vitae faucibus. Nam luctus eros nec mattis iaculis. Proin in sodales metus. In facilisis suscipit elementum. Nulla tristique quis arcu id pulvinar. Aenean eu faucibus nisi. In ex elit, sollicitudin ac eros id, malesuada auctor sapien. Curabitur eros dui, finibus nec fermentum quis, pellentesque id orci. Nullam eu tempus nulla. Vestibulum vitae metus nunc. Nullam quam magna, molestie at ultricies sit amet, sodales eget lacus. Maecenas ut nibh dictum, convallis elit nec, laoreet libero. Vivamus tempor porta lectus sit amet ornare. Vivamus at tellus et nulla consequat mollis quis vitae nisi. Curabitur sed lectus diam. Curabitur sodales vel justo ut pulvinar.  Curabitur vel imperdiet nulla. Integer venenatis dolor dui, non ultrices massa porta sed. Nunc egestas lacus eget ipsum lacinia egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur varius volutpat lacus eget euismod. Etiam ullamcorper ex augue, vel tempor sem varius eget. Nullam quis feugiat quam, nec lobortis enim. Duis mollis nunc id mi facilisis, quis laoreet est imperdiet. Integer dignissim accumsan eros. Morbi commodo tortor vel tortor tristique mollis. Duis ut elit gravida, rutrum diam id, ullamcorper dolor. Curabitur scelerisque justo a erat elementum, eget faucibus felis consequat. Phasellus convallis fringilla purus, non dapibus augue gravida at. Nulla lacinia maximus libero, ut cursus urna accumsan sed.</p>", "likedProfiles" : [20] },
  { "id" : 4,"author" : "deneme 1", "date" : "21 Temmuz 2021" ,"title" : "deneme 5", "description" : "deniyoz lalalalalallallalalalalallala","srcImage" : "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80","amountOfLikes" : 2,"avatar" : "/svg/logosoy-2.svg", "comments" : [ 
    { "author" : "Selam 1", "text" : "Lorem sıdhs sdhajsdn sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }, 
    { "author" : "Selam 2", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd sakdjks sasd", "date" : "23 Temmuz 2021" , "avatar" : "" }, 
    { "author" : "Selam 3", "text" : "Lorem sıdhs sdhajsdn asdjskdlaskd sjaksdmskd", "date" : "23 Temmuz 2021" , "avatar" : "/svg/logosoy-2.svg" }
  ],"text" : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales ipsum quis accumsan pellentesque. Aliquam fringilla pharetra scelerisque. Vestibulum vel dolor quis lacus laoreet faucibus in a purus. In imperdiet vulputate ullamcorper. Nam ultricies consectetur libero vitae faucibus. Nam luctus eros nec mattis iaculis. Proin in sodales metus. In facilisis suscipit elementum. Nulla tristique quis arcu id pulvinar. Aenean eu faucibus nisi. In ex elit, sollicitudin ac eros id, malesuada auctor sapien. Curabitur eros dui, finibus nec fermentum quis, pellentesque id orci. Nullam eu tempus nulla. Vestibulum vitae metus nunc. Nullam quam magna, molestie at ultricies sit amet, sodales eget lacus. Maecenas ut nibh dictum, convallis elit nec, laoreet libero. Vivamus tempor porta lectus sit amet ornare. Vivamus at tellus et nulla consequat mollis quis vitae nisi. Curabitur sed lectus diam. Curabitur sodales vel justo ut pulvinar.  Curabitur vel imperdiet nulla. Integer venenatis dolor dui, non ultrices massa porta sed. Nunc egestas lacus eget ipsum lacinia egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur varius volutpat lacus eget euismod. Etiam ullamcorper ex augue, vel tempor sem varius eget. Nullam quis feugiat quam, nec lobortis enim. Duis mollis nunc id mi facilisis, quis laoreet est imperdiet. Integer dignissim accumsan eros. Morbi commodo tortor vel tortor tristique mollis. Duis ut elit gravida, rutrum diam id, ullamcorper dolor. Curabitur scelerisque justo a erat elementum, eget faucibus felis consequat. Phasellus convallis fringilla purus, non dapibus augue gravida at. Nulla lacinia maximus libero, ut cursus urna accumsan sed.</p>", "likedProfiles" : [10,20] }
]

const postss = (posts = blogs, action) => {
    switch (action.type) {
      case "FETCH_ALL":
        return action.payload;
      case "LIKE":
        const blog = posts.filter(p => p.id === action.payload.id)[0]

        if(blog.likedProfiles.includes(action.payload.profileId)){
          if(action.payload.lnumber === -1){
            blog.amountOfLikes = blog.amountOfLikes + action.payload.lnumber
            blog.likedProfiles = blog.likedProfiles.filter(id => id !== action.payload.profileId)
          }

          return posts
        }

        blog.amountOfLikes = blog.amountOfLikes + action.payload.lnumber
        blog.likedProfiles.push(action.payload.profileId)

        return posts;
      case "CREATE":
        posts = [...posts, action.payload] 
        return [...posts, action.payload];
      case "UPDATE":
        return posts.map((post) => (post.id === action.payload.id ? action.payload : post));
      case "ADD_COMMENT":
        posts.filter(post => post.id === action.payload.id)[0].comments.push(action.payload.comment)
        return posts
      default:
        return posts;
    }
  };

  export default postss
